$file = 'c:\Users\ASUS\Desktop\bss system\resources\views\admin-dashboard.blade.php'
$content = Get-Content $file -Raw

# Add dropdown after input
$old1 = '                        <input type="text" x-model="fundraisingMemberSearch" @input="filterFundraisingMembers()" @focus="showFundraisingDropdown = true" @click="showFundraisingDropdown = true" @click.away="showFundraisingDropdown = false" placeholder="Search member..." class="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-pink-500 focus:border-pink-500 transition" autocomplete="off" required>' + "`r`n`r`n`r`n" + '                    </div>'

$new1 = '                        <input type="text" x-model="fundraisingMemberSearch" @input="filterFundraisingMembers()" @focus="showFundraisingDropdown = true" @click="showFundraisingDropdown = true" @click.away="showFundraisingDropdown = false" placeholder="Search member..." class="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-pink-500 focus:border-pink-500 transition" autocomplete="off" required>' + "`r`n" + '                        <div x-show="showFundraisingDropdown && filteredFundraisingMembers.length > 0" class="absolute z-10 w-full mt-1 bg-white border-2 border-pink-300 rounded-xl shadow-lg max-h-48 overflow-y-auto">' + "`r`n" + '                            <template x-for="member in filteredFundraisingMembers" :key="member.member_id">' + "`r`n" + '                                <div @click="selectFundraisingMember(member)" class="px-4 py-2 hover:bg-pink-50 cursor-pointer border-b border-gray-100 last:border-b-0">' + "`r`n" + '                                    <span class="font-semibold text-gray-800" x-text="member.member_id + '' - '' + member.full_name"></span>' + "`r`n" + '                                </div>' + "`r`n" + '                            </template>' + "`r`n" + '                        </div>' + "`r`n" + '                        <div x-show="fundraisingForm.member_id" class="mt-2 p-3 bg-pink-50 rounded-lg border border-pink-200">' + "`r`n" + '                            <p class="text-sm text-gray-700">💰 Current Savings: <span class="font-bold text-pink-600" x-text="formatCurrency(members.find(m => m.member_id === fundraisingForm.member_id)?.savings || 0)"></span></p>' + "`r`n" + '                        </div>' + "`r`n" + '                    </div>'

$content = $content.Replace($old1, $new1)

# Add notification and summary after purpose
$old2 = '                        <textarea x-model="fundraisingForm.purpose" class="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-pink-500 focus:border-pink-500 transition resize-y" rows="2" placeholder="Fundraising purpose" required></textarea>' + "`r`n`r`n" + '                    </div>' + "`r`n`r`n" + '                </div>'

$new2 = '                        <textarea x-model="fundraisingForm.purpose" class="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-pink-500 focus:border-pink-500 transition resize-y" rows="2" placeholder="Fundraising purpose" required></textarea>' + "`r`n" + '                    </div>' + "`r`n`r`n" + '                    <div class="md:col-span-2">' + "`r`n" + '                        <label class="flex items-center cursor-pointer">' + "`r`n" + '                            <input type="checkbox" x-model="fundraisingForm.send_notification" class="w-5 h-5 text-pink-600 rounded mr-3">' + "`r`n" + '                            <span class="text-sm font-medium text-gray-700">📧 Send notification to member</span>' + "`r`n" + '                        </label>' + "`r`n" + '                    </div>' + "`r`n`r`n" + '                    <div class="md:col-span-2 p-4 bg-gradient-to-br from-pink-50 to-rose-50 rounded-xl border-2 border-pink-200">' + "`r`n" + '                        <h4 class="font-bold text-gray-800 mb-3 flex items-center gap-2">' + "`r`n" + '                            <i class="fas fa-receipt text-pink-600"></i>' + "`r`n" + '                            Fundraising Summary' + "`r`n" + '                        </h4>' + "`r`n" + '                        <div class="space-y-2 text-sm">' + "`r`n" + '                            <div class="flex justify-between">' + "`r`n" + '                                <span class="text-gray-600">Campaign:</span>' + "`r`n" + '                                <span class="font-semibold text-gray-800" x-text="fundraisingForm.campaign_name || ''-''"></span>' + "`r`n" + '                            </div>' + "`r`n" + '                            <div class="flex justify-between">' + "`r`n" + '                                <span class="text-gray-600">Contribution Amount:</span>' + "`r`n" + '                                <span class="font-semibold text-gray-800" x-text="formatCurrency(fundraisingForm.amount || 0)"></span>' + "`r`n" + '                            </div>' + "`r`n" + '                            <div class="flex justify-between border-t-2 border-pink-300 pt-2 mt-2">' + "`r`n" + '                                <span class="font-bold text-gray-800">Total Contribution:</span>' + "`r`n" + '                                <span class="font-bold text-pink-600 text-lg" x-text="formatCurrency(fundraisingForm.amount || 0)"></span>' + "`r`n" + '                            </div>' + "`r`n" + '                        </div>' + "`r`n" + '                    </div>' + "`r`n" + '                </div>'

$content = $content.Replace($old2, $new2)

Set-Content $file $content
Write-Host "Fundraising modal completed"
