<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::unprepared(<<<'SQL'
CREATE TABLE bio_data (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    member_id BIGINT UNSIGNED UNIQUE NOT NULL,
    nin_number VARCHAR(50) UNIQUE,
    nin_issue_date DATE,
    nin_expiry_date DATE,
    nin_verified TINYINT(1) DEFAULT 0,
    nin_verified_at TIMESTAMP NULL,
    passport_number VARCHAR(50) UNIQUE,
    passport_issue_date DATE,
    passport_expiry_date DATE,
    passport_country VARCHAR(100),
    passport_verified TINYINT(1) DEFAULT 0,
    driving_license VARCHAR(50) UNIQUE,
    license_issue_date DATE,
    license_expiry_date DATE,
    license_class VARCHAR(50),
    license_verified TINYINT(1) DEFAULT 0,
    voter_id VARCHAR(50) UNIQUE,
    voter_id_verified TINYINT(1) DEFAULT 0,
    marital_status_id TINYINT UNSIGNED,
    wedding_date DATE,
    number_of_children TINYINT DEFAULT 0,
    spouse_name VARCHAR(191),
    spouse_nin VARCHAR(50),
    spouse_dob DATE,
    spouse_phone VARCHAR(50),
    spouse_email VARCHAR(191),
    spouse_occupation VARCHAR(191),
    spouse_employer VARCHAR(191),
    father_name VARCHAR(191),
    father_alive TINYINT(1) DEFAULT 1,
    father_phone VARCHAR(50),
    father_occupation VARCHAR(191),
    father_address_id BIGINT UNSIGNED NULL,
    mother_name VARCHAR(191),
    mother_alive TINYINT(1) DEFAULT 1,
    mother_phone VARCHAR(50),
    mother_occupation VARCHAR(191),
    mother_address_id BIGINT UNSIGNED NULL,
    next_of_kin_name VARCHAR(191) NOT NULL,
    next_of_kin_relationship VARCHAR(100) NOT NULL,
    next_of_kin_phone VARCHAR(50) NOT NULL,
    next_of_kin_email VARCHAR(191),
    next_of_kin_nin VARCHAR(50),
    next_of_kin_dob DATE,
    next_of_kin_occupation VARCHAR(191),
    next_of_kin_address_id BIGINT UNSIGNED,
    next_of_kin_is_minor TINYINT(1) DEFAULT 0,
    next_of_kin_guardian_name VARCHAR(191),
    alt_next_of_kin_name VARCHAR(191),
    alt_next_of_kin_relationship VARCHAR(100),
    alt_next_of_kin_phone VARCHAR(50),
    alt_next_of_kin_email VARCHAR(191),
    alt_next_of_kin_address_id BIGINT UNSIGNED,
    children JSON DEFAULT NULL COMMENT 'Array of {name, dob, gender, school, guardian}',
    highest_education VARCHAR(191),
    school_name VARCHAR(191),
    school_address_id BIGINT UNSIGNED NULL,
    professional_qualifications JSON,
    employment_status_id TINYINT UNSIGNED,
    employer_name VARCHAR(191),
    employer_address_id BIGINT UNSIGNED NULL,
    employer_phone VARCHAR(50),
    employer_email VARCHAR(191),
    job_title VARCHAR(191),
    job_description TEXT,
    employment_start_date DATE,
    employment_end_date DATE,
    monthly_income DECIMAL(15,2),
    income_frequency ENUM('daily', 'weekly', 'monthly', 'annually') DEFAULT 'monthly',
    other_income_sources JSON,
    business_name VARCHAR(191),
    business_type VARCHAR(100),
    business_address_id BIGINT UNSIGNED NULL,
    business_phone VARCHAR(50),
    business_email VARCHAR(191),
    business_registration VARCHAR(100),
    business_license VARCHAR(100),
    business_start_date DATE,
    business_monthly_revenue DECIMAL(15,2),
    business_monthly_expenses DECIMAL(15,2),
    bank_name VARCHAR(191),
    bank_branch VARCHAR(191),
    bank_account_number VARCHAR(100),
    bank_account_name VARCHAR(191),
    bank_verified TINYINT(1) DEFAULT 0,
    bank_verified_at TIMESTAMP NULL,
    bank_alternative JSON COMMENT 'Alternative bank accounts',
    mobile_money_number VARCHAR(50),
    mobile_money_provider ENUM('mtn', 'airtel', 'africell', 'lycamobile', 'other'),
    mobile_money_name VARCHAR(191),
    mobile_money_verified TINYINT(1) DEFAULT 0,
    mobile_money_verified_at TIMESTAMP NULL,
    emergency_contact_name VARCHAR(191) NOT NULL,
    emergency_contact_relationship VARCHAR(100) NOT NULL,
    emergency_contact_phone VARCHAR(50) NOT NULL,
    emergency_contact_alternative VARCHAR(50),
    emergency_contact_email VARCHAR(191),
    emergency_contact_address_id BIGINT UNSIGNED NULL,
    social_media JSON COMMENT 'Object with facebook, twitter, linkedin, etc.',
    has_disability TINYINT(1) DEFAULT 0,
    disability_details TEXT,
    blood_group VARCHAR(5),
    allergies TEXT,
    medical_conditions TEXT,
    signature_path VARCHAR(255),
    signature_data TEXT,
    declaration_date DATE,
    declaration_ip VARCHAR(45),
    declaration_location VARCHAR(255),
    declaration_latitude DECIMAL(10,8),
    declaration_longitude DECIMAL(11,8),
    consent_sms TINYINT(1) DEFAULT 1,
    consent_email TINYINT(1) DEFAULT 1,
    consent_whatsapp TINYINT(1) DEFAULT 0,
    consent_push TINYINT(1) DEFAULT 1,
    data_processing_consent TINYINT(1) DEFAULT 0,
    consent_date TIMESTAMP NULL,
    verified_by BIGINT UNSIGNED NULL,
    verified_at TIMESTAMP NULL,
    verification_notes TEXT,
    notes TEXT,
    tags JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    updated_by BIGINT UNSIGNED NULL,
    INDEX idx_bio_member (member_id),
    INDEX idx_bio_nin (nin_number),
    INDEX idx_bio_passport (passport_number),
    INDEX idx_bio_driving (driving_license),
    INDEX idx_bio_next_of_kin (next_of_kin_phone),
    INDEX idx_bio_emergency (emergency_contact_phone),
    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    FOREIGN KEY (marital_status_id) REFERENCES marital_statuses(id),
    FOREIGN KEY (employment_status_id) REFERENCES employment_statuses(id),
    FOREIGN KEY (father_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (mother_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (next_of_kin_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (alt_next_of_kin_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (school_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (employer_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (business_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (emergency_contact_address_id) REFERENCES member_addresses(id),
    FOREIGN KEY (verified_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
)
SQL);
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }

    public function down(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::statement('DROP TABLE IF EXISTS `bio_data`');
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
};
